from function2widgets.widgets.misc import Color

from ._trs import *


FUNC_NAME = TR_FUNC_NAME
DEFAULT_BARCODE_TYPE = "code39"
DEFAULT_BARCODE_EXTRA_ARGS = None

DEFAULT_MODULE_WIDTH = 0.2
DEFAULT_MODULE_HEIGHT = 15.0
DEFAULT_QUIET_ZONE = 6.5
DEFAULT_FONT_PATH = "DejaVuSansMono"
DEFAULT_FONT_SIZE = 10
DEFAULT_TEXT_DISTANCE = 5.0
DEFAULT_BACKGROUND = Color.from_string("white")
DEFAULT_FOREGROUND = Color.from_string("black")
DEFAULT_CENTER_TEXT = True